config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  scope :for_display, -> { order(:created_at).last(50) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_validation :set_default_type, if: Proc.new { |user| user.type.blank? }

  validates_presence_of :first_name, :last_name
  validates_inclusion_of :type, in: %w[Trainer User]

  has_many :messages

  def set_default_type
    self.type = 'User'
  end
end

app/models/users/trainer.rb
class Trainer < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[first_name last_name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_messages

  def index
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chat_room_channel',
                                   message: render_message(message)
    end
  end

  private

  def get_messages
    @messages = Message.for_display
    @message = current_user.messages.build
  end

  def message_params
    params.require(:message).permit(:content)
  end

  def render_message(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="container center-align">
  <h1 style="color: #B00100; padding-top: 20px">Welcome to the Dashboard</h1>

  <div class="waves-effect waves-light btn"><i class="material-icons left">message</i>
    <%= link_to 'Join the Conversation', messages_path, style: "color: #ffffff" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatAppRails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<% if current_user %>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Chat App</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to('Log out', destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
<% end %>
</nav>
<%= yield %>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <%= message.user.first_name %>:
  </div>
  <div class="message-content">
    <%= message.content %>
  </div>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= form_for(@message, remote: true) do |f| %>
    <%= f.text_area :content %>
    <label>
      <i class="material-icons right">send</i>
      <%= f.submit "Send" %>
    </label>

  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
  <div id="messages-table" class="messages-table">
    <% if @messages.any? %>
      <%= render @messages %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="message-wr">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>